runtime: python38  # Pythonのバージョンを指定します。使用しているバージョンに合わせて変更してください。
entrypoint: gunicorn -w 3 -b :$PORT --timeout 120 BackEnd.app:app

#includes:
#- secret.yaml

env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1  # 必要に応じてスケールする最大インスタンス数

#env_variables:
#  B_INSTANCE: "one-page-408108.uc.r.appspot.com"
